version: '3.8'

services:
  postgres_db:
    container_name: postgres_db
    image: postgres:16.2
    volumes:
      - ./database_dump/movies_database_dump.sql:/docker-entrypoint-initdb.d/movies_database_dump.sql:ro
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    networks:
      - custom_network
    expose:
      - ${POSTGRES_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  redis_cache:
    container_name: redis_cache
    image: redis:7.2.4
    networks:
      - custom_network
    expose:
      - ${REDIS_PORT}
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.7.1
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - custom_network
    ports:
      - "${ELASTIC_PORT}:${ELASTIC_PORT}"
    healthcheck:
       test: curl -s http://${ELASTIC_HOST}:${ELASTIC_PORT} >/dev/null || exit 1
       interval: 30s
       timeout: 10s
       retries: 50

  etl_scheduler:
    container_name: "etl_scheduler"
    image: docker.io/versuffer2024/etl:latest
    restart: always
    environment:
      POSTGRES_HOST: postgres_db
      ELASTIC_HOST: elasticsearch
    networks:
      - custom_network
    depends_on:
      postgres_db:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

volumes:
  postgres_data:

networks:
  custom_network:
    external: false
    driver: bridge
